// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsproject.proto

package grpc.dsproject;

public interface CalculateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dsproject.CalculateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double calories = 1;</code>
   */
  double getCalories();

  /**
   * <code>string caloriesmessage = 2;</code>
   */
  java.lang.String getCaloriesmessage();
  /**
   * <code>string caloriesmessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getCaloriesmessageBytes();
}
