// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsproject.proto

package grpc.dsproject;

/**
 * Protobuf type {@code dsproject.CalculateRequest}
 */
public  final class CalculateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dsproject.CalculateRequest)
    CalculateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CalculateRequest.newBuilder() to construct.
  private CalculateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CalculateRequest() {
    number1_ = 0D;
    operation_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CalculateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            number1_ = input.readDouble();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            operation_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.dsproject.ProjectServiceImpl.internal_static_dsproject_CalculateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.dsproject.ProjectServiceImpl.internal_static_dsproject_CalculateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.dsproject.CalculateRequest.class, grpc.dsproject.CalculateRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code dsproject.CalculateRequest.Operation}
   */
  public enum Operation
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>walking = 0;</code>
     */
    walking(0),
    /**
     * <code>briskwalking = 1;</code>
     */
    briskwalking(1),
    /**
     * <code>jogging = 2;</code>
     */
    jogging(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>walking = 0;</code>
     */
    public static final int walking_VALUE = 0;
    /**
     * <code>briskwalking = 1;</code>
     */
    public static final int briskwalking_VALUE = 1;
    /**
     * <code>jogging = 2;</code>
     */
    public static final int jogging_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Operation valueOf(int value) {
      return forNumber(value);
    }

    public static Operation forNumber(int value) {
      switch (value) {
        case 0: return walking;
        case 1: return briskwalking;
        case 2: return jogging;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Operation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Operation> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
            public Operation findValueByNumber(int number) {
              return Operation.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return grpc.dsproject.CalculateRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Operation[] VALUES = values();

    public static Operation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Operation(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dsproject.CalculateRequest.Operation)
  }

  public static final int NUMBER1_FIELD_NUMBER = 1;
  private double number1_;
  /**
   * <code>double number1 = 1;</code>
   */
  public double getNumber1() {
    return number1_;
  }

  public static final int OPERATION_FIELD_NUMBER = 2;
  private int operation_;
  /**
   * <code>.dsproject.CalculateRequest.Operation operation = 2;</code>
   */
  public int getOperationValue() {
    return operation_;
  }
  /**
   * <code>.dsproject.CalculateRequest.Operation operation = 2;</code>
   */
  public grpc.dsproject.CalculateRequest.Operation getOperation() {
    @SuppressWarnings("deprecation")
    grpc.dsproject.CalculateRequest.Operation result = grpc.dsproject.CalculateRequest.Operation.valueOf(operation_);
    return result == null ? grpc.dsproject.CalculateRequest.Operation.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (number1_ != 0D) {
      output.writeDouble(1, number1_);
    }
    if (operation_ != grpc.dsproject.CalculateRequest.Operation.walking.getNumber()) {
      output.writeEnum(2, operation_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (number1_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, number1_);
    }
    if (operation_ != grpc.dsproject.CalculateRequest.Operation.walking.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, operation_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.dsproject.CalculateRequest)) {
      return super.equals(obj);
    }
    grpc.dsproject.CalculateRequest other = (grpc.dsproject.CalculateRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getNumber1())
        == java.lang.Double.doubleToLongBits(
            other.getNumber1()));
    result = result && operation_ == other.operation_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUMBER1_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNumber1()));
    hash = (37 * hash) + OPERATION_FIELD_NUMBER;
    hash = (53 * hash) + operation_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.dsproject.CalculateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.dsproject.CalculateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.dsproject.CalculateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.dsproject.CalculateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.dsproject.CalculateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.dsproject.CalculateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.dsproject.CalculateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.dsproject.CalculateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.dsproject.CalculateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.dsproject.CalculateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.dsproject.CalculateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.dsproject.CalculateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.dsproject.CalculateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dsproject.CalculateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dsproject.CalculateRequest)
      grpc.dsproject.CalculateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.dsproject.ProjectServiceImpl.internal_static_dsproject_CalculateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.dsproject.ProjectServiceImpl.internal_static_dsproject_CalculateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.dsproject.CalculateRequest.class, grpc.dsproject.CalculateRequest.Builder.class);
    }

    // Construct using grpc.dsproject.CalculateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      number1_ = 0D;

      operation_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.dsproject.ProjectServiceImpl.internal_static_dsproject_CalculateRequest_descriptor;
    }

    @java.lang.Override
    public grpc.dsproject.CalculateRequest getDefaultInstanceForType() {
      return grpc.dsproject.CalculateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.dsproject.CalculateRequest build() {
      grpc.dsproject.CalculateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.dsproject.CalculateRequest buildPartial() {
      grpc.dsproject.CalculateRequest result = new grpc.dsproject.CalculateRequest(this);
      result.number1_ = number1_;
      result.operation_ = operation_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.dsproject.CalculateRequest) {
        return mergeFrom((grpc.dsproject.CalculateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.dsproject.CalculateRequest other) {
      if (other == grpc.dsproject.CalculateRequest.getDefaultInstance()) return this;
      if (other.getNumber1() != 0D) {
        setNumber1(other.getNumber1());
      }
      if (other.operation_ != 0) {
        setOperationValue(other.getOperationValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.dsproject.CalculateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.dsproject.CalculateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double number1_ ;
    /**
     * <code>double number1 = 1;</code>
     */
    public double getNumber1() {
      return number1_;
    }
    /**
     * <code>double number1 = 1;</code>
     */
    public Builder setNumber1(double value) {
      
      number1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double number1 = 1;</code>
     */
    public Builder clearNumber1() {
      
      number1_ = 0D;
      onChanged();
      return this;
    }

    private int operation_ = 0;
    /**
     * <code>.dsproject.CalculateRequest.Operation operation = 2;</code>
     */
    public int getOperationValue() {
      return operation_;
    }
    /**
     * <code>.dsproject.CalculateRequest.Operation operation = 2;</code>
     */
    public Builder setOperationValue(int value) {
      operation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.dsproject.CalculateRequest.Operation operation = 2;</code>
     */
    public grpc.dsproject.CalculateRequest.Operation getOperation() {
      @SuppressWarnings("deprecation")
      grpc.dsproject.CalculateRequest.Operation result = grpc.dsproject.CalculateRequest.Operation.valueOf(operation_);
      return result == null ? grpc.dsproject.CalculateRequest.Operation.UNRECOGNIZED : result;
    }
    /**
     * <code>.dsproject.CalculateRequest.Operation operation = 2;</code>
     */
    public Builder setOperation(grpc.dsproject.CalculateRequest.Operation value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      operation_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.dsproject.CalculateRequest.Operation operation = 2;</code>
     */
    public Builder clearOperation() {
      
      operation_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dsproject.CalculateRequest)
  }

  // @@protoc_insertion_point(class_scope:dsproject.CalculateRequest)
  private static final grpc.dsproject.CalculateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.dsproject.CalculateRequest();
  }

  public static grpc.dsproject.CalculateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CalculateRequest>
      PARSER = new com.google.protobuf.AbstractParser<CalculateRequest>() {
    @java.lang.Override
    public CalculateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CalculateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CalculateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CalculateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.dsproject.CalculateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

