// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsproject2.proto

package grpc.dsproject;

public interface CalculateRequest2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:dsproject2.CalculateRequest2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double weight = 1;</code>
   */
  double getWeight();
}
