// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsproject3.proto

package grpc.dsproject;

public interface CalculateResponse3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:dsproject3.CalculateResponse3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double calories3 = 1;</code>
   */
  double getCalories3();

  /**
   * <code>string caloriesmessage3 = 2;</code>
   */
  java.lang.String getCaloriesmessage3();
  /**
   * <code>string caloriesmessage3 = 2;</code>
   */
  com.google.protobuf.ByteString
      getCaloriesmessage3Bytes();
}
