// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsproject2.proto

package grpc.dsproject;

public interface CalculateResponse2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:dsproject2.CalculateResponse2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double water = 1;</code>
   */
  double getWater();

  /**
   * <code>string watermessage = 2;</code>
   */
  java.lang.String getWatermessage();
  /**
   * <code>string watermessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getWatermessageBytes();
}
