// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsproject2.proto

package grpc.dsproject;

/**
 * Protobuf type {@code dsproject2.CalculateResponse2}
 */
public  final class CalculateResponse2 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dsproject2.CalculateResponse2)
    CalculateResponse2OrBuilder {
private static final long serialVersionUID = 0L;
  // Use CalculateResponse2.newBuilder() to construct.
  private CalculateResponse2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CalculateResponse2() {
    water_ = 0D;
    watermessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CalculateResponse2(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            water_ = input.readDouble();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            watermessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.dsproject.ProjectService2Impl.internal_static_dsproject2_CalculateResponse2_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.dsproject.ProjectService2Impl.internal_static_dsproject2_CalculateResponse2_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.dsproject.CalculateResponse2.class, grpc.dsproject.CalculateResponse2.Builder.class);
  }

  public static final int WATER_FIELD_NUMBER = 1;
  private double water_;
  /**
   * <code>double water = 1;</code>
   */
  public double getWater() {
    return water_;
  }

  public static final int WATERMESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object watermessage_;
  /**
   * <code>string watermessage = 2;</code>
   */
  public java.lang.String getWatermessage() {
    java.lang.Object ref = watermessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      watermessage_ = s;
      return s;
    }
  }
  /**
   * <code>string watermessage = 2;</code>
   */
  public com.google.protobuf.ByteString
      getWatermessageBytes() {
    java.lang.Object ref = watermessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      watermessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (water_ != 0D) {
      output.writeDouble(1, water_);
    }
    if (!getWatermessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, watermessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (water_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, water_);
    }
    if (!getWatermessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, watermessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.dsproject.CalculateResponse2)) {
      return super.equals(obj);
    }
    grpc.dsproject.CalculateResponse2 other = (grpc.dsproject.CalculateResponse2) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getWater())
        == java.lang.Double.doubleToLongBits(
            other.getWater()));
    result = result && getWatermessage()
        .equals(other.getWatermessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WATER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWater()));
    hash = (37 * hash) + WATERMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getWatermessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.dsproject.CalculateResponse2 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.dsproject.CalculateResponse2 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.dsproject.CalculateResponse2 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.dsproject.CalculateResponse2 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.dsproject.CalculateResponse2 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.dsproject.CalculateResponse2 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.dsproject.CalculateResponse2 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.dsproject.CalculateResponse2 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.dsproject.CalculateResponse2 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.dsproject.CalculateResponse2 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.dsproject.CalculateResponse2 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.dsproject.CalculateResponse2 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.dsproject.CalculateResponse2 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dsproject2.CalculateResponse2}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dsproject2.CalculateResponse2)
      grpc.dsproject.CalculateResponse2OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.dsproject.ProjectService2Impl.internal_static_dsproject2_CalculateResponse2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.dsproject.ProjectService2Impl.internal_static_dsproject2_CalculateResponse2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.dsproject.CalculateResponse2.class, grpc.dsproject.CalculateResponse2.Builder.class);
    }

    // Construct using grpc.dsproject.CalculateResponse2.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      water_ = 0D;

      watermessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.dsproject.ProjectService2Impl.internal_static_dsproject2_CalculateResponse2_descriptor;
    }

    @java.lang.Override
    public grpc.dsproject.CalculateResponse2 getDefaultInstanceForType() {
      return grpc.dsproject.CalculateResponse2.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.dsproject.CalculateResponse2 build() {
      grpc.dsproject.CalculateResponse2 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.dsproject.CalculateResponse2 buildPartial() {
      grpc.dsproject.CalculateResponse2 result = new grpc.dsproject.CalculateResponse2(this);
      result.water_ = water_;
      result.watermessage_ = watermessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.dsproject.CalculateResponse2) {
        return mergeFrom((grpc.dsproject.CalculateResponse2)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.dsproject.CalculateResponse2 other) {
      if (other == grpc.dsproject.CalculateResponse2.getDefaultInstance()) return this;
      if (other.getWater() != 0D) {
        setWater(other.getWater());
      }
      if (!other.getWatermessage().isEmpty()) {
        watermessage_ = other.watermessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.dsproject.CalculateResponse2 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.dsproject.CalculateResponse2) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double water_ ;
    /**
     * <code>double water = 1;</code>
     */
    public double getWater() {
      return water_;
    }
    /**
     * <code>double water = 1;</code>
     */
    public Builder setWater(double value) {
      
      water_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double water = 1;</code>
     */
    public Builder clearWater() {
      
      water_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object watermessage_ = "";
    /**
     * <code>string watermessage = 2;</code>
     */
    public java.lang.String getWatermessage() {
      java.lang.Object ref = watermessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        watermessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string watermessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getWatermessageBytes() {
      java.lang.Object ref = watermessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        watermessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string watermessage = 2;</code>
     */
    public Builder setWatermessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      watermessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string watermessage = 2;</code>
     */
    public Builder clearWatermessage() {
      
      watermessage_ = getDefaultInstance().getWatermessage();
      onChanged();
      return this;
    }
    /**
     * <code>string watermessage = 2;</code>
     */
    public Builder setWatermessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      watermessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dsproject2.CalculateResponse2)
  }

  // @@protoc_insertion_point(class_scope:dsproject2.CalculateResponse2)
  private static final grpc.dsproject.CalculateResponse2 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.dsproject.CalculateResponse2();
  }

  public static grpc.dsproject.CalculateResponse2 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CalculateResponse2>
      PARSER = new com.google.protobuf.AbstractParser<CalculateResponse2>() {
    @java.lang.Override
    public CalculateResponse2 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CalculateResponse2(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CalculateResponse2> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CalculateResponse2> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.dsproject.CalculateResponse2 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

