// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsproject.proto

package grpc.dsproject;

public interface CalculateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dsproject.CalculateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double number1 = 1;</code>
   */
  double getNumber1();

  /**
   * <code>.dsproject.CalculateRequest.Operation operation = 2;</code>
   */
  int getOperationValue();
  /**
   * <code>.dsproject.CalculateRequest.Operation operation = 2;</code>
   */
  grpc.dsproject.CalculateRequest.Operation getOperation();
}
