// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsproject3.proto

package grpc.dsproject;

public interface CalculateRequest3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:dsproject3.CalculateRequest3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double weight2 = 1;</code>
   */
  double getWeight2();

  /**
   * <code>double height = 2;</code>
   */
  double getHeight();

  /**
   * <code>double age = 3;</code>
   */
  double getAge();

  /**
   * <code>.dsproject3.CalculateRequest3.Operation3 operation3 = 4;</code>
   */
  int getOperation3Value();
  /**
   * <code>.dsproject3.CalculateRequest3.Operation3 operation3 = 4;</code>
   */
  grpc.dsproject.CalculateRequest3.Operation3 getOperation3();
}
