// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsproject3.proto

package grpc.dsproject;

/**
 * Protobuf type {@code dsproject3.CalculateResponse3}
 */
public  final class CalculateResponse3 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dsproject3.CalculateResponse3)
    CalculateResponse3OrBuilder {
private static final long serialVersionUID = 0L;
  // Use CalculateResponse3.newBuilder() to construct.
  private CalculateResponse3(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CalculateResponse3() {
    calories3_ = 0D;
    caloriesmessage3_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CalculateResponse3(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            calories3_ = input.readDouble();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            caloriesmessage3_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.dsproject.ProjectService3Impl.internal_static_dsproject3_CalculateResponse3_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.dsproject.ProjectService3Impl.internal_static_dsproject3_CalculateResponse3_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.dsproject.CalculateResponse3.class, grpc.dsproject.CalculateResponse3.Builder.class);
  }

  public static final int CALORIES3_FIELD_NUMBER = 1;
  private double calories3_;
  /**
   * <code>double calories3 = 1;</code>
   */
  public double getCalories3() {
    return calories3_;
  }

  public static final int CALORIESMESSAGE3_FIELD_NUMBER = 2;
  private volatile java.lang.Object caloriesmessage3_;
  /**
   * <code>string caloriesmessage3 = 2;</code>
   */
  public java.lang.String getCaloriesmessage3() {
    java.lang.Object ref = caloriesmessage3_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      caloriesmessage3_ = s;
      return s;
    }
  }
  /**
   * <code>string caloriesmessage3 = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCaloriesmessage3Bytes() {
    java.lang.Object ref = caloriesmessage3_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      caloriesmessage3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (calories3_ != 0D) {
      output.writeDouble(1, calories3_);
    }
    if (!getCaloriesmessage3Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, caloriesmessage3_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (calories3_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, calories3_);
    }
    if (!getCaloriesmessage3Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, caloriesmessage3_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.dsproject.CalculateResponse3)) {
      return super.equals(obj);
    }
    grpc.dsproject.CalculateResponse3 other = (grpc.dsproject.CalculateResponse3) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getCalories3())
        == java.lang.Double.doubleToLongBits(
            other.getCalories3()));
    result = result && getCaloriesmessage3()
        .equals(other.getCaloriesmessage3());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CALORIES3_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCalories3()));
    hash = (37 * hash) + CALORIESMESSAGE3_FIELD_NUMBER;
    hash = (53 * hash) + getCaloriesmessage3().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.dsproject.CalculateResponse3 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.dsproject.CalculateResponse3 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.dsproject.CalculateResponse3 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.dsproject.CalculateResponse3 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.dsproject.CalculateResponse3 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.dsproject.CalculateResponse3 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.dsproject.CalculateResponse3 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.dsproject.CalculateResponse3 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.dsproject.CalculateResponse3 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.dsproject.CalculateResponse3 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.dsproject.CalculateResponse3 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.dsproject.CalculateResponse3 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.dsproject.CalculateResponse3 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dsproject3.CalculateResponse3}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dsproject3.CalculateResponse3)
      grpc.dsproject.CalculateResponse3OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.dsproject.ProjectService3Impl.internal_static_dsproject3_CalculateResponse3_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.dsproject.ProjectService3Impl.internal_static_dsproject3_CalculateResponse3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.dsproject.CalculateResponse3.class, grpc.dsproject.CalculateResponse3.Builder.class);
    }

    // Construct using grpc.dsproject.CalculateResponse3.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      calories3_ = 0D;

      caloriesmessage3_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.dsproject.ProjectService3Impl.internal_static_dsproject3_CalculateResponse3_descriptor;
    }

    @java.lang.Override
    public grpc.dsproject.CalculateResponse3 getDefaultInstanceForType() {
      return grpc.dsproject.CalculateResponse3.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.dsproject.CalculateResponse3 build() {
      grpc.dsproject.CalculateResponse3 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.dsproject.CalculateResponse3 buildPartial() {
      grpc.dsproject.CalculateResponse3 result = new grpc.dsproject.CalculateResponse3(this);
      result.calories3_ = calories3_;
      result.caloriesmessage3_ = caloriesmessage3_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.dsproject.CalculateResponse3) {
        return mergeFrom((grpc.dsproject.CalculateResponse3)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.dsproject.CalculateResponse3 other) {
      if (other == grpc.dsproject.CalculateResponse3.getDefaultInstance()) return this;
      if (other.getCalories3() != 0D) {
        setCalories3(other.getCalories3());
      }
      if (!other.getCaloriesmessage3().isEmpty()) {
        caloriesmessage3_ = other.caloriesmessage3_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.dsproject.CalculateResponse3 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.dsproject.CalculateResponse3) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double calories3_ ;
    /**
     * <code>double calories3 = 1;</code>
     */
    public double getCalories3() {
      return calories3_;
    }
    /**
     * <code>double calories3 = 1;</code>
     */
    public Builder setCalories3(double value) {
      
      calories3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double calories3 = 1;</code>
     */
    public Builder clearCalories3() {
      
      calories3_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object caloriesmessage3_ = "";
    /**
     * <code>string caloriesmessage3 = 2;</code>
     */
    public java.lang.String getCaloriesmessage3() {
      java.lang.Object ref = caloriesmessage3_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        caloriesmessage3_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string caloriesmessage3 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCaloriesmessage3Bytes() {
      java.lang.Object ref = caloriesmessage3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        caloriesmessage3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string caloriesmessage3 = 2;</code>
     */
    public Builder setCaloriesmessage3(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      caloriesmessage3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string caloriesmessage3 = 2;</code>
     */
    public Builder clearCaloriesmessage3() {
      
      caloriesmessage3_ = getDefaultInstance().getCaloriesmessage3();
      onChanged();
      return this;
    }
    /**
     * <code>string caloriesmessage3 = 2;</code>
     */
    public Builder setCaloriesmessage3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      caloriesmessage3_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dsproject3.CalculateResponse3)
  }

  // @@protoc_insertion_point(class_scope:dsproject3.CalculateResponse3)
  private static final grpc.dsproject.CalculateResponse3 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.dsproject.CalculateResponse3();
  }

  public static grpc.dsproject.CalculateResponse3 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CalculateResponse3>
      PARSER = new com.google.protobuf.AbstractParser<CalculateResponse3>() {
    @java.lang.Override
    public CalculateResponse3 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CalculateResponse3(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CalculateResponse3> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CalculateResponse3> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.dsproject.CalculateResponse3 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

