// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsproject3.proto

package grpc.dsproject;

public final class ProjectService3Impl {
  private ProjectService3Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dsproject3_CalculateRequest3_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dsproject3_CalculateRequest3_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dsproject3_CalculateResponse3_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dsproject3_CalculateResponse3_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020dsproject3.proto\022\ndsproject3\"\243\001\n\021Calcu" +
      "lateRequest3\022\017\n\007weight2\030\001 \001(\001\022\016\n\006height\030" +
      "\002 \001(\001\022\013\n\003age\030\003 \001(\001\022<\n\noperation3\030\004 \001(\0162(" +
      ".dsproject3.CalculateRequest3.Operation3" +
      "\"\"\n\nOperation3\022\010\n\004male\020\000\022\n\n\006female\020\001\"A\n\022" +
      "CalculateResponse3\022\021\n\tcalories3\030\001 \001(\001\022\030\n" +
      "\020caloriesmessage3\030\002 \001(\t2`\n\017ProjectServic" +
      "e3\022M\n\ncalculate3\022\035.dsproject3.CalculateR" +
      "equest3\032\036.dsproject3.CalculateResponse3\"" +
      "\000B\'\n\016grpc.dsprojectB\023ProjectService3Impl" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dsproject3_CalculateRequest3_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dsproject3_CalculateRequest3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dsproject3_CalculateRequest3_descriptor,
        new java.lang.String[] { "Weight2", "Height", "Age", "Operation3", });
    internal_static_dsproject3_CalculateResponse3_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dsproject3_CalculateResponse3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dsproject3_CalculateResponse3_descriptor,
        new java.lang.String[] { "Calories3", "Caloriesmessage3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
